const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    
    //
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //addmin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',
   
    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',
    
    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    ////
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',
    
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',
    
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',
    
    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED: 'FETCH_ALL_USER_FAILED',
    
    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAILED: 'FETCH_TOP_DOCTOR_FAILED',
    
    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILED: 'FETCH_ALL_DOCTOR_FAILED',
    
    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',
    
    FETCH_DETAIL_DOCTOR_ID_SUCCESS: 'FETCH_DETAIL_DOCTOR_ID_SUCCESS',
    FETCH_DETAIL_DOCTOR_ID_FAILED: 'FETCH_DETAIL_DOCTOR_ID_FAILED',
    
    EDIT_DETAIL_DOCTOR_SUCCESS: 'EDIT_DETAIL_DOCTOR_SUCCESS',
    EDIT_DETAIL_DOCTOR_FAILED: 'EDIT_DETAIL_DOCTOR_FAILED',
    
    FETCH_ALL_CODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALL_CODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALL_CODE_SCHEDULE_TIME_FAILED: 'FETCH_ALL_CODE_SCHEDULE_TIME_FAILED',
    
    BULK_CREATE_SCHEDULE_SUCCESS: 'BULK_CREATE_SCHEDULE_SUCCESS',
    BULK_CREATE_SCHEDULE_FAILED: 'BULK_CREATE_SCHEDULE_FAILED',
    
    FETCH_SCHEDULE_BY_DATE_SUCCESS: 'FETCH_SCHEDULE_BY_DATE_SUCCESS',
    FETCH_SCHEDULE_BY_DATE_FAILED: 'FETCH_SCHEDULE_BY_DATE_FAILED',
    
    FETCH_REQUIRE_DOCTOR_INFO_START: 'FETCH_REQUIRE_DOCTOR_INFO_START',
    FETCH_REQUIRE_DOCTOR_INFO_SUCCESS: 'FETCH_REQUIRE_DOCTOR_INFO_SUCCESS',
    FETCH_REQUIRE_DOCTOR_INFO_FAILED: 'FETCH_REQUIRE_DOCTOR_INFO_FAILED',
    
    SAVE_DOCTOR_INFO_SUCCESS: 'SAVE_DOCTOR_INFO_SUCCESS',
    SAVE_DOCTOR_INFO_FAILED: 'SAVE_DOCTOR_INFO_FAILED',
    
    FETCH_DOCTOR_INFO_SUCCESS: 'FETCH_DOCTOR_INFO_SUCCESS',
    FETCH_DOCTOR_INFO_FAILED: 'FETCH_DOCTOR_INFO_FAILED',
   
    
    
    FETCH_PROFILE_DOCTOR_SUCCESS: 'FETCH_PROFILE_DOCTOR_SUCCESS',
    FETCH_PROFILE_DOCTOR_FAILED: 'FETCH_PROFILE_DOCTOR_FAILED',
   
    FETCH_ALL_SPECIALTY_SUCCESS: 'FETCH_ALL_SPECIALTY_SUCCESS',
    FETCH_ALL_SPECIALTY_FAILED: 'FETCH_ALL_SPECIALTY_FAILED',
   
    FETCH_DETAIL_SPECIALTY_SUCCESS: 'FETCH_DETAIL_SPECIALTY_SUCCESS',
    FETCH_DETAIL_SPECIALTY_FAILED: 'FETCH_DETAIL_SPECIALTY_FAILED',
    
    CREATE_CLINIC_SUCCESS: 'CREATE_CLINIC_SUCCESS',
    CREATE_CLINIC_FAILED: 'CREATE_CLINIC_FAILED',
    
    GET_ALL_CLINIC_SUCCESS: 'GET_ALL_CLINIC_SUCCESS',
    GET_ALL_CLINIC_FAILED: 'GET_ALL_CLINIC_FAILED',
})

export default actionTypes;